# Generated by Django 4.2.3 on 2023-07-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamam_Far3y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tamam_Type',
            new_name='Tamam_Asasy',
        ),
        migrations.RenameField(
            model_name='tamam',
            old_name='tamam_type',
            new_name='tamam_asasy',
        ),
        migrations.AddField(
            model_name='tamam',
            name='tamam_far3y',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.tamam_far3y'),
            preserve_default=False,
        ),
    ]
