# Generated by Django 4.2.3 on 2023-07-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tamam_far3y_rename_tamam_type_tamam_asasy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamam_far3y',
            name='tamam_asasy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.tamam_asasy'),
            preserve_default=False,
        ),
    ]
