# Generated by Django 4.2.3 on 2023-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tamam_far3y_tamam_asasy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamam_far3y',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
