# Generated by Django 4.2.3 on 2023-07-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tamam_far3y_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamam',
            name='tamam_asasy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tamam_asasy'),
        ),
        migrations.AlterField(
            model_name='tamam',
            name='tamam_far3y',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tamam_far3y'),
        ),
    ]
