# Generated by Django 4.2.3 on 2023-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tamam_tamam_asasy_alter_tamam_tamam_far3y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamam',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
