# Generated by Django 4.2.3 on 2023-07-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_qeta3_nadafa_alter_tamam_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamam',
            name='tamam_asasy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tamam_asasy'),
        ),
    ]
