# Generated by Django 4.2.3 on 2023-07-22 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_tamam_tamam_asasy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daily_nadafa',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='daily_nadafa',
            name='qeta3_nadafa',
        ),
        migrations.AddField(
            model_name='daily_nadafa',
            name='qeta3_nadafa',
            field=models.ManyToManyField(to='home.qeta3_nadafa'),
        ),
    ]
