# Generated by Django 4.2.3 on 2023-07-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_daily_nadafa_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_nadafa',
            old_name='qeta3_nadafa',
            new_name='qeta3at_nadafa',
        ),
    ]
