# Generated by Django 4.2.3 on 2023-07-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_qeta3_nadafa_daily_nadafa_qeta3at_nadafa'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_nadafa',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
