# Generated by Django 4.2.3 on 2023-07-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_daily_nadafa_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_nadafa',
            name='weight',
        ),
    ]
